language: ruby
before_install:
- gem update --system
addons:
  postgresql: "11"
rvm:
- 2.6.2
services:
- postgresql
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
before_script:
- psql -c 'create database planaway_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake
- bundle exec rubocop
- bundle exec brakeman
deploy:
  provider: heroku
  app: iheartplanning
  api_key:
    secure: A09g0R6chQahKqn6jwcdjs6lxFkBn7SyLyzdqhyq00dVR9QDKtjetKIYpGgk/eslSPZncH7odMMhcrp6L5753IctFSVIQAIyq4VD28tbsd/1baa2tuGE/8TvTbWke8qTY8mqocm5YZndEIRi7UQ8tImoJTgaP/piKIN/uhxISAXuct6TbmBDF3NMQqe1VZDCbSaSN/6SnXnTtgyIJyfbSmCU8bjnW0W4YbQlRHRH0cqW9xVngGvf/0AapaYOZcMKZ9ZkRl38jbYGoo8viQkn0ON5MdnlbXeP5s31gWHhW3mQfAsTpZbxU1b+Ijw5mOcxYc/p+dL+Ju7LtDaSIRCm5KW8i0MjNxBV9vO9Jwh82flhFdKWLQTO8TX86VihQLbvUD0OXLebuQ5fxNmMYgcvOnaD99Fq4rt+hSb/kcbxMOQgquwJD3JgInGOovG84E3L9C5O5a4U1vW8Scf6t6QnEFLXS1LuJmH+vOmerdGQaTfeDJ8vgfIaRWa7mnXfGcdBYk5ooL5/TBfq7Ievsh04C20r0WHD1u2HbEEsTPSrGhSPflTxqelcZ3XSC+Pcpch2ZGsrnFs4vZxeTz+6DstwsIuH15F6r2mfBzFnVi5Ff/qxxGR3WihtAuMZoZW7rpRwGeVgQ+A5gNQvX6qUqsRwXYQSl9CPvtHOH9nVph1wtSE=
