language: ruby
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
- gem update --system
- sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
- sudo /etc/init.d/postgresql restart
env:
  global:
  - PGPORT=5433
rvm:
- 2.6.2
services:
- postgresql
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
before_script:
- psql -c 'create database planaway_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake
- bundle exec rubocop
- bundle exec brakeman
deploy:
  provider: heroku
  app: iheartplanning
  api_key:
    secure: SxKdKQNbg5pP9OMdwstBiCOVjsq/kSzz50gUhICHumlepuMMQ+av+Nqb8joF1hIXHeT90LVpS2eWZQBPitn1DgnVnX/H6OyAXI/rMAx9ElgWwVWgEy9juGU8Yp7fNEsilyJTBhfl+63lQsJvo3iMNFweF5QHKZFRrRgcfd/MfsTaViijzYSMfK60zElNk5SUx9vay2no8CJkEqpvvP4qHDHo1tZYrCVW0RJB3U5ux9TouFE372/Zcm/lnQmYt4VGrGazLKJz4AVQgeWYD/bWDx8CuTELreTQDCedX/1K6PuMx8L+QtqygE8dvT5fHO028uADCFwbkNqwdVptuVPKRFOILEiNDtuZV7DHfH9UHAEAjaX16Jm1WXvO7taIhiYXjgu2iQBNTmUhzhl1kC0NWFTI/P6DusJ5xElaUN9iP69Mrl68CD1xJlCUrDB3YdZzzYOk228GO/JjYJffedWf0NgBNwd2jKzLLKe3Q5AydsSHAXDNWGz5j7xFSooNiJ64fx1H2VoRJdNgwF2gQ2aZ5QrawvflGv9CZcRsUJo17dL3jsW8CP0/XLRRYor+Jd53t58P4wWEEcFuZl+s6CAKrRcUAMkeoYZf3pF/BH5HPqSpkOWp2EEcw6DHn6+/X3DyYaGbdcR9b92Br6NrjU59/5od9Yl5WYiOY8VyLCWIbxY=
